/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get System */
        get: operations["get_system_api_v1_system_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scenarios */
        get: operations["get_scenarios_api_v1_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Run */
        post: operations["start_run_api_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Events */
        get: operations["get_run_events_api_v1_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intakes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Intake */
        post: operations["upload_intake_api_v1_intakes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intakes/{intake_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Intake */
        get: operations["read_intake_api_v1_intakes__intake_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intakes/{intake_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Intake */
        post: operations["confirm_intake_api_v1_intakes__intake_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intakes/{intake_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Intake Run */
        post: operations["start_intake_run_api_v1_intakes__intake_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/decision-package.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Decision Package */
        get: operations["download_decision_package_api_v1_runs__run_id__decision_package_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Approvals */
        get: operations["get_approvals_api_v1_approvals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/{loan_id}/{gate}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Approval Decision */
        post: operations["post_approval_decision_api_v1_approvals__loan_id___gate__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluation/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evaluation Report */
        get: operations["get_evaluation_report_api_v1_evaluation_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Evaluation */
        post: operations["start_evaluation_api_v1_evaluations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/{evaluation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evaluation */
        get: operations["get_evaluation_api_v1_evaluations__evaluation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_v1_documents__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentRunView */
        AgentRunView: {
            /** Agent */
            agent: string;
            /** Task */
            task: string;
            /** Seconds */
            seconds: number;
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Completion Tokens */
            completion_tokens: number;
            /** Usd */
            usd: number;
            /** Delegated To */
            delegated_to?: string | null;
            /** Tools Called */
            tools_called?: string[];
            /**
             * Replayed
             * @default false
             */
            replayed?: boolean;
        };
        /**
         * ApprovalDecisionBody
         * @description `loan_id` and `gate` are path parameters; the body carries only the decision
         *     inputs plus the artifact digest the browser must echo back unchanged.
         */
        ApprovalDecisionBody: {
            /** Artifact Digest */
            artifact_digest: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "approved" | "rejected";
            /** Approver */
            approver: string;
        };
        /** ApprovalItem */
        ApprovalItem: {
            /** Loan Id */
            loan_id: string;
            /** Gate */
            gate: string;
            /** Status */
            status: string;
            /** Approver */
            approver?: string | null;
            /** Artifact Digest */
            artifact_digest: string;
            /** Artifact */
            artifact: {
                [key: string]: unknown;
            };
            /** Requested At */
            requested_at: number;
            /** Decided At */
            decided_at?: number | null;
        };
        /** ApprovalQueueResponse */
        ApprovalQueueResponse: {
            /** Approvals */
            approvals: components["schemas"]["ApprovalItem"][];
        };
        /** Body_upload_intake_api_v1_intakes_post */
        Body_upload_intake_api_v1_intakes_post: {
            /** Files */
            files: string[];
        };
        /** CitationView */
        CitationView: {
            /** Corpus */
            corpus: string;
            /** Section */
            section: string;
            /** Claim */
            claim: string;
            /** Applied To */
            applied_to?: string | null;
            /** Quoted */
            quoted?: string | null;
            /** Exists */
            exists?: boolean | null;
            /** Supports Claim */
            supports_claim?: boolean | null;
            /** Entailed */
            entailed?: boolean | null;
            /** Verified */
            verified?: boolean | null;
            /** Qc Note */
            qc_note?: string | null;
        };
        /** CompensationView */
        CompensationView: {
            /** Step */
            step: string;
            /** Outcome */
            outcome: string;
            /** Note */
            note: string;
            /** Detail */
            detail?: {
                [key: string]: unknown;
            };
        };
        /** ConditionView */
        ConditionView: {
            /** Kind */
            kind: string;
            /** Description */
            description: string;
            /** Citation */
            citation?: string | null;
            /** Raised By */
            raised_by: string;
        };
        /** CycleTimeView */
        CycleTimeView: {
            /** Scope */
            scope?: string | null;
            /** Basis */
            basis?: string | null;
            /** Baseline Days */
            baseline_days?: number | null;
            /** Baseline Touch Minutes */
            baseline_touch_minutes?: number | null;
            /** Modeled Days */
            modeled_days?: number | null;
            /** Irreducible Floor Days */
            irreducible_floor_days?: number | null;
            /** Baseline Underwriter Touches */
            baseline_underwriter_touches?: number | null;
            /** Modeled Underwriter Touches */
            modeled_underwriter_touches?: number | null;
            /** Measured Agent Seconds */
            measured_agent_seconds?: number | null;
            /** Does Not Compress */
            does_not_compress?: string[];
        };
        /**
         * Decision
         * @enum {string}
         */
        Decision: "approved" | "approved_with_conditions" | "suspended" | "denied" | "incomplete";
        /** DocumentResponse */
        DocumentResponse: {
            /**
             * Slug
             * @enum {string}
             */
            slug: "architecture" | "assumptions";
            /** Title */
            title: string;
            /** Markdown */
            markdown: string;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            detail: components["schemas"]["ErrorResponse"];
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Active Run Id */
            active_run_id?: string | null;
            /** Active Evaluation Id */
            active_evaluation_id?: string | null;
        };
        /** EvaluationReportResponse */
        EvaluationReportResponse: {
            /** Exists */
            exists: boolean;
            /** Markdown */
            markdown: string;
            /** Path */
            path: string;
            /** Modified At */
            modified_at?: number | null;
        };
        /**
         * EvaluationStatusResponse
         * @description A reconnectable snapshot consumed by the evaluation page.
         */
        EvaluationStatusResponse: {
            /** Evaluation Id */
            evaluation_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "completed" | "failed";
            /** Returncode */
            returncode?: number | null;
            /**
             * Output
             * @default
             */
            output?: string;
            report?: components["schemas"]["EvaluationReportResponse"] | null;
            /** Error Message */
            error_message?: string | null;
            /** Started At */
            started_at: string;
            /** Terminal At */
            terminal_at?: string | null;
        };
        /** EventEnvelope */
        EventEnvelope: {
            /** Id */
            id: number;
            /** Run Id */
            run_id: string;
            /** Type */
            type: string;
            /** Actor */
            actor: string;
            /** Loan Id */
            loan_id?: string | null;
            /** Timestamp */
            timestamp: string;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
            /** Line */
            line: string;
        };
        /** FindingView */
        FindingView: {
            /** Severity */
            severity: string;
            /** Kind */
            kind: string;
            /** Detail */
            detail: string;
        };
        /** GuidelineFindingView */
        GuidelineFindingView: {
            /** Question */
            question: string;
            /** Rounds Used */
            rounds_used?: number | null;
            /** Sufficient */
            sufficient?: boolean | null;
            /** Citations */
            citations?: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IdempotencyView */
        IdempotencyView: {
            /**
             * Enabled
             * @default false
             */
            enabled?: boolean;
            /** Calls Before Second Run */
            calls_before_second_run?: number | null;
            /** Calls After Second Run */
            calls_after_second_run?: number | null;
        };
        /** IntakeConfirmationBody */
        IntakeConfirmationBody: {
            /** Reviewer */
            reviewer: string;
            /** Expected Revision */
            expected_revision: number;
            /** Case */
            case: {
                [key: string]: unknown;
            };
        };
        /** IntakeRunRequest */
        IntakeRunRequest: {
            /**
             * Judgment Kind
             * @default stub
             * @enum {string}
             */
            judgment_kind?: "stub" | "crew";
            /**
             * Roster
             * @default production
             * @enum {string}
             */
            roster?: "production" | "demo";
            /**
             * Auto Approve
             * @default false
             */
            auto_approve?: boolean;
        };
        /** LedgerEntryView */
        LedgerEntryView: {
            /** Id */
            id: number;
            /** Step */
            step: string;
            /** Phase */
            phase: string;
            /** Outcome */
            outcome: string;
            /** Idempotency Key */
            idempotency_key?: string | null;
            /** Detail */
            detail?: {
                [key: string]: unknown;
            };
            /** Timestamp */
            timestamp: number;
        };
        /** LoanRunResult */
        LoanRunResult: {
            /** Loan Id */
            loan_id: string;
            /** Scenario Id */
            scenario_id?: number | null;
            /** Scenario Name */
            scenario_name: string;
            decision?: components["schemas"]["Decision"] | null;
            /**
             * Decision Rationale
             * @default
             */
            decision_rationale?: string;
            /** Expected Decision */
            expected_decision?: string | null;
            /** Expected Matches */
            expected_matches?: boolean | null;
            /** Overlays */
            overlays?: components["schemas"]["OverlayConflictView"][];
            value_acceptance?: components["schemas"]["ValueAcceptanceView"];
            /** Conditions */
            conditions?: components["schemas"]["ConditionView"][];
            /** Citations */
            citations?: components["schemas"]["CitationView"][];
            /** Qc Findings */
            qc_findings?: components["schemas"]["FindingView"][];
            /** Controls Fired */
            controls_fired?: string[];
            /** Guideline Findings */
            guideline_findings?: components["schemas"]["GuidelineFindingView"][];
            /** Ledger */
            ledger?: components["schemas"]["LedgerEntryView"][];
            /** Compensation */
            compensation?: components["schemas"]["CompensationView"][];
            /** Notices */
            notices?: components["schemas"]["NoticeView"][];
            cycle_time?: components["schemas"]["CycleTimeView"] | null;
            /** Agent Runs */
            agent_runs?: components["schemas"]["AgentRunView"][];
            /**
             * Tri Merge Calls
             * @default 0
             */
            tri_merge_calls?: number;
            idempotency?: components["schemas"]["IdempotencyView"];
        };
        /** NoticeView */
        NoticeView: {
            /** Kind */
            kind: string;
            /** Issued On */
            issued_on: string;
            /** Due On */
            due_on: string;
            /** Citation */
            citation?: string | null;
            /** Reasons */
            reasons?: string[];
        };
        /** OverlayConflictView */
        OverlayConflictView: {
            /** Dimension */
            dimension: string;
            /** Actual */
            actual?: unknown;
            /** Agency */
            agency?: unknown;
            /** Overlay */
            overlay?: unknown;
            /** Citation */
            citation?: string | null;
            /**
             * Exception Granted
             * @default false
             */
            exception_granted?: boolean;
        };
        /**
         * RunResponse
         * @description A reconnectable snapshot consumed by the case workspace.
         */
        RunResponse: {
            /** Run Id */
            run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "completed" | "awaiting_approval" | "failed";
            /** Mode */
            mode?: string | null;
            scenario?: components["schemas"]["ScenarioOption"] | null;
            /** Events */
            events?: components["schemas"]["EventEnvelope"][];
            /** Trace Lines */
            trace_lines?: string[];
            result?: components["schemas"]["LoanRunResult"] | null;
            /** Approval */
            approval?: {
                [key: string]: unknown;
            } | null;
            /** Error Type */
            error_type?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Terminal At */
            terminal_at?: string | null;
            /** Terminal Persistence Error */
            terminal_persistence_error?: string | null;
        };
        /** ScenarioOption */
        ScenarioOption: {
            /** Scenario Id */
            scenario_id: number;
            /** Label */
            label: string;
            /** Name */
            name: string;
            /** Loan Id */
            loan_id: string;
            /** Expected Decision */
            expected_decision?: string | null;
            /** Summary */
            summary?: string | null;
        };
        /** StartEvaluationResponse */
        StartEvaluationResponse: {
            /** Evaluation Id */
            evaluation_id: string;
            /**
             * Status
             * @constant
             */
            status: "running";
        };
        /** StartRunRequest */
        StartRunRequest: {
            /** Scenario Id */
            scenario_id: number;
            /**
             * Judgment Kind
             * @default stub
             * @enum {string}
             */
            judgment_kind?: "stub" | "crew";
            /**
             * Roster
             * @default production
             * @enum {string}
             */
            roster?: "production" | "demo";
            /**
             * Policy Attack
             * @default false
             */
            policy_attack?: boolean;
            /**
             * Submit Twice
             * @default false
             */
            submit_twice?: boolean;
            /**
             * Auto Approve
             * @default false
             */
            auto_approve?: boolean;
        };
        /** StartRunResponse */
        StartRunResponse: {
            /** Run Id */
            run_id: string;
            /**
             * Status
             * @constant
             */
            status: "running";
        };
        /** SystemResponse */
        SystemResponse: {
            /** Version */
            version: string;
            /** Api Key Present */
            api_key_present: boolean;
            /**
             * Default Judgment
             * @enum {string}
             */
            default_judgment: "stub" | "crew";
            /** Active Run Id */
            active_run_id?: string | null;
            /** Active Evaluation Id */
            active_evaluation_id?: string | null;
            /** Crew Available */
            crew_available: boolean;
            /** Crew Unavailable Reason */
            crew_unavailable_reason?: string | null;
            /** Crew Setup Action */
            crew_setup_action?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValueAcceptanceView */
        ValueAcceptanceView: {
            /**
             * Offered
             * @default false
             */
            offered?: boolean;
            /** Exercised */
            exercised?: boolean | null;
            /**
             * Rationale
             * @default
             */
            rationale?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_system_api_v1_system_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemResponse"];
                };
            };
        };
    };
    get_scenarios_api_v1_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioOption"][];
                };
            };
        };
    };
    start_run_api_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartRunResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_events_api_v1_runs__run_id__events_get: {
        parameters: {
            query?: {
                last_event_id?: number | null;
            };
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["EventEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    upload_intake_api_v1_intakes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_intake_api_v1_intakes_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Invalid document intake */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    read_intake_api_v1_intakes__intake_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                intake_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Intake or run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Invalid document intake */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    confirm_intake_api_v1_intakes__intake_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                intake_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntakeConfirmationBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Intake or run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Intake or run state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Invalid document intake */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    start_intake_run_api_v1_intakes__intake_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                intake_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntakeRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartRunResponse"];
                };
            };
            /** @description Intake or run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Intake or run state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Invalid document intake */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    download_decision_package_api_v1_runs__run_id__decision_package_pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Decision package PDF attachment */
            200: {
                headers: {
                    /** @description Attachment filename */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            /** @description Intake or run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Intake or run state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_approvals_api_v1_approvals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalQueueResponse"];
                };
            };
        };
    };
    post_approval_decision_api_v1_approvals__loan_id___gate__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                loan_id: string;
                gate: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalDecisionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_evaluation_report_api_v1_evaluation_report_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationReportResponse"];
                };
            };
        };
    };
    start_evaluation_api_v1_evaluations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartEvaluationResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_evaluation_api_v1_evaluations__evaluation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationStatusResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_v1_documents__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: "architecture" | "assumptions";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
